script: |
  docker pull xabhi/backend-app
  docker pull xabhi/frontend-app
  docker pull mongo

  docker network inspect app-network >/dev/null 2>&1 || docker network create app-network

  docker rm -f backend frontend mongo || true

  # ✅ Start MongoDB
  docker run -d \
    --name mongo \
    --network app-network \
    -p 27017:27017 \
    mongo

  # ✅ Start Backend
  docker run -d \
    --name backend \
    --network app-network \
    -p 5000:5000 \
    --env-file .env \
    xabhi/backend-app

  # ✅ Start Frontend
  docker run -d \
    --name frontend \
    --network app-network \
    -p 3000:80 \
    xabhi/frontend-app