name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker pull xabhi/backend-app
            docker pull xabhi/frontend-app

            docker network inspect app-network >/dev/null 2>&1 || docker network create app-network

            docker rm -f backend frontend || true

            docker run -d --name backend --network app-network -p 5000:5000 --env-file .env xabhi/backend-app
            docker run -d --name frontend --network app-network -p 3000:80 xabhi/frontend-app